version: '3.8'

services:
  redis:
    image: redis:alpine3.19


  django:
    image: mannyebi/soran:web
    container_name: Imazh
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    environment:
      - ALLOWED_HOSTS=localhost:80,0.0.0.1,soran.liara.run
      - DEBUG=True
      - SECRET_KEY=fdsfsdfdsnjkfngfdjgfgidjo
      - TZ=Asia/Tehran
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery --app=imazh worker -l info
    volumes:
      - .:/app/
    environment:
      - ALLOWED_HOSTS=localhost:80,0.0.0.1,soran.liara.run
      - DEBUG=True
      - SECRET_KEY=fdsfsdfdsnjkfngfdjgfgidjo
      - TZ=Asia/Tehran
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A imazh beat -l INFO
    volumes:
      - .:/app/
    depends_on:
      - redis
