# Generated by Django 4.2.5 on 2023-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_appointment_appdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appdate',
            field=models.DateTimeField(),
        ),
    ]
