# Generated by Django 4.2.5 on 2023-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_appointment_appdate_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM'), ('4:30 PM', '4:30 PM'), ('5:30 PM', '5:30 PM'), ('6:30 PM', '6:30 PM'), ('7:30 PM', '7:30 PM'), ('8:30 PM', '8:30 PM'), ('9:30 PM', '9:30 PM'), ('10:30 PM', '10:30 PM')], default='3 PM', max_length=10),
        ),
    ]
