# Generated by Django 4.2.7 on 2023-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('1:00 PM', '1:00 PM'), ('4:30 PM', '4:30 PM'), ('5:30 PM', '5:30 PM'), ('6:30 PM', '6:30 PM'), ('7:30 PM', '7:30 PM'), ('8:30 PM', '8:30 PM'), ('9:30 PM', '9:30 PM'), ('10:30 PM', '10:30 PM')], default='3 PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True),
        ),
    ]
