# Generated by Django 5.0 on 2024-02-19 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='شماره تلفن باید حداقل 11 رقم بوده و با 09 شروع شود')]),
        ),
    ]
