# Generated by Django 5.0 on 2024-03-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
