# Generated by Django 5.0 on 2024-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_appointment_time_datetime_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_datetime',
            field=models.TimeField(),
        ),
    ]
