# Generated by Django 5.0 on 2024-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='upload/team1.png', null=True, upload_to=''),
        ),
    ]
