# Generated by Django 5.0 on 2024-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='deactive_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
    ]
